version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current  
    resource_class: medium

    steps:
      - checkout
      
      - run: mkdir nano

      - restore_cache:
          keys:
            - largefile-cache-{{ checksum "largefile.dat" }}
            - largefile-cache-

      - run:
          name: Generate 800MB File
          command: |
            dd if=/dev/urandom of=nano/largefile.dat bs=1M count=800

      - save_cache:
          key: largefile-cache-{{ checksum "largefile.dat" }}
          paths:
            - nano/largefile.dat

      - run:
          name: Verify File
          command: |
            if [ -f nano/largefile.dat ]; then
              echo "File restored successfully."
              ls -lh nano/largefile.dat
            else
              echo "File not found."
              exit 1
            fi
            
      - restore_cache:
          keys:
            - small-cache-{{ checksum "nano/smallfile.dat" }}
            - small-cache-

      - run:
          name: Generate 800MB File
          command: |
            dd if=/dev/urandom of=nano/smallfile.dat bs=1M count=300

      - save_cache:
          key: smallfile-cache-{{ checksum "nano/smallfile.dat" }}
          paths:
            - nano/smallfile.dat

      - run:
          name: Verify File
          command: |
            if [ -f nano/smallfile.dat ]; then
              echo "File restored successfully."
              ls -lh nano/smallfile.dat
            else
              echo "File not found."
              exit 1
            fi
