version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current  
    resource_class: medium

    steps:
      - checkout
      
      - run: mkdir nano
      - run:
          name: Set cache week
          command: echo 'export CACHE_WEEK=$(date +%Y-%U)' >> "$BASH_ENV"

      - run:
          name: Check cache week
          command: echo $CACHE_WEEK

      - restore_cache:
          keys:
            - largefile-cache-main-{{ .BuildNum }}-{{ .Environment.CACHE_WEEK }}
            - largefile-cache-main-{{ .BuildNum }} 
            - largefile-cache-main-
            - largefile-cache-

      - run:
          name: Generate 800MB File
          command: |
            #dd if=/dev/urandom of=nano/largefile-0.dat bs=1M count=1800
            #dd if=/dev/urandom of=nano/largefile-1.dat bs=1M count=800
            #dd if=/dev/urandom of=nano/largefile-2.dat bs=1M count=800
            dd if=/dev/urandom of=nano/largefile-3.dat bs=1M count=300

      - save_cache:
          key: largefile-cache-main-{{ .BuildNum }}-{{ .Environment.CACHE_WEEK}}
          paths:
            - nano

      - run:
          name: Verify File
          command: |
            if [ -f nano/largefile-3.dat ]; then
              echo "File restored successfully."
              ls -lh nano/
            else
              echo "File not found."
              exit 1
            fi
            
      - restore_cache:
          keys:
            - small-cache-main-{{ .BuildNum }} 
            - small-cache-main-
            - small-cache-

      - run:
          name: Generate 800MB File
          command: |
            dd if=/dev/urandom of=nano/smallfile.dat bs=1M count=300

      - save_cache:
          key: smallfile-cache-main
          paths:
            - nano
      
      - store_artifacts:
         path: nano/

      - run:
          name: Verify File
          command: |
            if [ -f nano/smallfile.dat ]; then
              echo "File restored successfully."
              ls -lh nano/smallfile.dat
            else
              echo "File not found."
              exit 1
            fi
